// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGitHubInstallation = `-- name: CreateGitHubInstallation :one
INSERT INTO github_installations (
    team_id, installation_id, account_type, account_login, account_id
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (installation_id) DO UPDATE SET
    team_id = EXCLUDED.team_id,
    account_type = EXCLUDED.account_type,
    account_login = EXCLUDED.account_login,
    account_id = EXCLUDED.account_id,
    suspended_at = NULL,
    updated_at = NOW()
RETURNING id, team_id, installation_id, account_type, account_login, account_id, suspended_at, created_at, updated_at
`

type CreateGitHubInstallationParams struct {
	TeamID         pgtype.UUID `db:"team_id" json:"team_id"`
	InstallationID int64       `db:"installation_id" json:"installation_id"`
	AccountType    string      `db:"account_type" json:"account_type"`
	AccountLogin   string      `db:"account_login" json:"account_login"`
	AccountID      int64       `db:"account_id" json:"account_id"`
}

func (q *Queries) CreateGitHubInstallation(ctx context.Context, arg CreateGitHubInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, createGitHubInstallation,
		arg.TeamID,
		arg.InstallationID,
		arg.AccountType,
		arg.AccountLogin,
		arg.AccountID,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.InstallationID,
		&i.AccountType,
		&i.AccountLogin,
		&i.AccountID,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGitHubInstallation = `-- name: DeleteGitHubInstallation :exec
DELETE FROM github_installations WHERE installation_id = $1
`

func (q *Queries) DeleteGitHubInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.Exec(ctx, deleteGitHubInstallation, installationID)
	return err
}

const getGitHubInstallation = `-- name: GetGitHubInstallation :one
SELECT id, team_id, installation_id, account_type, account_login, account_id, suspended_at, created_at, updated_at FROM github_installations WHERE id = $1
`

func (q *Queries) GetGitHubInstallation(ctx context.Context, id pgtype.UUID) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getGitHubInstallation, id)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.InstallationID,
		&i.AccountType,
		&i.AccountLogin,
		&i.AccountID,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitHubInstallationByInstallationID = `-- name: GetGitHubInstallationByInstallationID :one
SELECT id, team_id, installation_id, account_type, account_login, account_id, suspended_at, created_at, updated_at FROM github_installations WHERE installation_id = $1
`

func (q *Queries) GetGitHubInstallationByInstallationID(ctx context.Context, installationID int64) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getGitHubInstallationByInstallationID, installationID)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.InstallationID,
		&i.AccountType,
		&i.AccountLogin,
		&i.AccountID,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamGitHubInstallations = `-- name: GetTeamGitHubInstallations :many
SELECT id, team_id, installation_id, account_type, account_login, account_id, suspended_at, created_at, updated_at FROM github_installations
WHERE team_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTeamGitHubInstallations(ctx context.Context, teamID pgtype.UUID) ([]GithubInstallation, error) {
	rows, err := q.db.Query(ctx, getTeamGitHubInstallations, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubInstallation{}
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.InstallationID,
			&i.AccountType,
			&i.AccountLogin,
			&i.AccountID,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suspendGitHubInstallation = `-- name: SuspendGitHubInstallation :exec
UPDATE github_installations
SET suspended_at = NOW(), updated_at = NOW()
WHERE installation_id = $1
`

func (q *Queries) SuspendGitHubInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.Exec(ctx, suspendGitHubInstallation, installationID)
	return err
}

const unsuspendGitHubInstallation = `-- name: UnsuspendGitHubInstallation :exec
UPDATE github_installations
SET suspended_at = NULL, updated_at = NOW()
WHERE installation_id = $1
`

func (q *Queries) UnsuspendGitHubInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.Exec(ctx, unsuspendGitHubInstallation, installationID)
	return err
}
