// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GithubInstallation struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	TeamID         pgtype.UUID        `db:"team_id" json:"team_id"`
	InstallationID int64              `db:"installation_id" json:"installation_id"`
	AccountType    string             `db:"account_type" json:"account_type"`
	AccountLogin   string             `db:"account_login" json:"account_login"`
	AccountID      int64              `db:"account_id" json:"account_id"`
	SuspendedAt    pgtype.Timestamptz `db:"suspended_at" json:"suspended_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Team struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	Name                 string             `db:"name" json:"name"`
	Slug                 string             `db:"slug" json:"slug"`
	StripeSubscriptionID pgtype.Text        `db:"stripe_subscription_id" json:"stripe_subscription_id"`
	Plan                 string             `db:"plan" json:"plan"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamMember struct {
	TeamID    pgtype.UUID        `db:"team_id" json:"team_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Role      string             `db:"role" json:"role"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	GithubID         int64              `db:"github_id" json:"github_id"`
	GithubUsername   string             `db:"github_username" json:"github_username"`
	Email            pgtype.Text        `db:"email" json:"email"`
	AvatarUrl        pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	StripeCustomerID pgtype.Text        `db:"stripe_customer_id" json:"stripe_customer_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
